### PR TITLE
Create ShaikhTheWorld.html

### PR DESCRIPTION
**Pull request by ShaikhTheWorld**
I am trying to add my username to the 'humans directory', but I'm still really confused.
Do let me know if there's a better way to do this, or if I need to make some changes to make this work.

Thanks in advance! :D

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
Your file name name should be named as "ShaikhTheWorld.html".

**Comment by SubhrajyotiSen** [comment]
You can also take a look at the other files to get an idea.

**Comment by aaossa** [comment]
Hey @ShaikhTheWorld , any updates on this? :eyes: :speak_no_evil:

**Comment by aaossa** [comment]
Sorry, I'll close this because of inactivity @ShaikhTheWorld . If you want me to open this again just leave us a comment :)

**Pull request closed without merging**
