### PR TITLE
Added VamsiSangam.html

### PR DESCRIPTION
**Pull request by VamsiSangam**
Added VamsiSangam.html and added my username to human.txt. I hope I am doing all this correctly.

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
Yup! You have done it all correct :smiley:

**Comment by VamsiSangam** [comment]
I am a noob. Please guide me. This is what I did -

1. Forked muan's repo.
2. Cloned the forked repo into my local machine.
3. Created a new branch.
4. Aded html page and edited human.txt
5. Merged new branch to gh-pages in local machine.
6. Pushed changes to the forked repo in my account.
7. Created pull request.

Have I done everything correctly? Is this the standard way of contributing to a public repo?

**Comment by SubhrajyotiSen** [comment]
You don't need to merge the new branch on your local copy. Usually while contributing, you make the pull request from the new branch that you create.
Instructions regarding this are mentioned in the repository's docs

**Comment by VamsiSangam** [comment]
Oh, I didn't know we can do that. So, if I do all my edits to a new branch, say "gh-pages-edits", then, I go to my GitHub, navigate to the "gh-pages-edit" branch and then create a pull request from there to muan's repo? Is this correct? What is more proper, editing the master branch after the fork and then creating pull request from master, or editing a new branch from master from forked repo and then creating pull request from the new branch? Sorry to be a bother.

**Comment by SubhrajyotiSen** [comment]
Yes. You can create a pull request from the new branch you made. 
It is preferable to add your changes to the a new branch rather than master branch while making a pull request.

**Comment by VamsiSangam** [comment]
Ok. Thanks a lot. Great repo for beginners to get started! :)

**Comment by SubhrajyotiSen** [comment]
All credits to @muan

**Pull request merged**
