### PR TITLE
add zwirektech to human.txt

### PR DESCRIPTION
**Pull request by zwirektech**

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
Hey! Can you please add your HTML file in the same PR. Since they are linked

**Review by SubhrajyotiSen — DISMISSED** [review]

**Comment by zwirektech** [comment]
Well, they are not linked in any way. That's why I wanted to change a few things.
There is more "user files" than usernames in human.txt. There are also usernames in human.txt without coresponding html files. For now, I can see no reason to create a html file. 
I'd like to learn more git and github, by cleaning up such issues in this repo.
For now I've learned to do one thing at a time...

**Comment by SubhrajyotiSen** [comment]
The index page displays the images of all the users mentioned in humans.txt. Clicking on the image loads up the corresponding HTML file. So if there is no HTML file, it will just cause a 404 error

**Review by aaossa — DISMISSED** [review]
You need to add your html file (`zwirektech.html`)

**Comment by zwirektech** [comment]
Clicking on the image does not load HTML file. There is a username "nik849" in the human.txt with corresponding HTML file nik849.txt
How is it possible? Are we looking at the same source?

**Comment by SubhrajyotiSen** [comment]
<strike>That is one small anomaly. </strike>

**Comment by zwirektech** [comment]
Not really. The script doesn't look at these files at all.
In the end it might turn out that my changes were good, but not discussed...

**Comment by muan** [comment]
Hey @zwirektech, you are right in that those files are indeed not linked. However, **both** adding your username to `humans.txt` _and_ adding a username named file are [the tasks suggested in the README](https://github.com/muan/hello-world#not-sure-what-to-do). The bonus ones are optional. 

And yes, the username named file doesn't need to be HTML file either as suggested in the readme, which is why I approved and merged #87. :)

**Comment by zwirektech** [comment]
Hey @muan, 
I don't argue with this. I'm here to learn how to use git and github. This conversation is a part of this process, so thank you for helping me understand how it works.
I just wanted to commit a few changes, which in my opinion are coherent with your repo policy. Unfortunately I've made to many changes in one [pull request and it is closed now](
https://github.com/muan/hello-world/pull/90).
However it looks like we will all agree with those changes if discussed extensively.
To be honest, I thought you make a change first, than discuss it, to merge it to the master at some time.

**Comment by muan** [comment]
> I don't argue with this. I'm here to learn how to use git and github. This conversation is a part of this process, so thank you for helping me understand how it works.

:+1: Totally agree. I think conversation is the biggest part of collaboration on GitHub.

> I just wanted to commit a few changes, which in my opinion are coherent with your repo policy. Unfortunately I've made to many changes in one pull request and it is closed now.

Ah, sorry, I completely missed #90 so didn't have that context. 

Yes, if you still have interests in taking on #92, please do. Just remember as @SubhrajyotiSen mentioned in #90, keep each PR focus to one purpose.

> To be honest, I thought you make a change first, than discuss it, to merge it to the master at some time.

That's OK in many cases. But in cases where changes require non trivial changes and may have bigger impact to the project, it's best to open an issue to discuss the details first. This is good practice because then you can make sure your efforts won't go to waste.

**Comment by zwirektech** [comment]
> Ah, sorry, I completely missed #90 so didn't have that context.
> Yes, if you still have interests in taking on #92, please do. Just remember as @SubhrajyotiSen mentioned in #90, keep each PR focus to one purpose.

Yes, I have. 
But I'd like to use the work which is already done at [my fork of hello-world](https://github.com/zwirektech/hello-world)
Can I split my changes to different branches and make a pull request separately on each of it?

It would be:
- [update human.txt - add zwirektech](
https://github.com/zwirektech/hello-world/commit/f9b84f255341fcfd6bc4a103fae3d35c8dd6d983) - which is already requested as #91. I've edited the file again at [muan:gh-pages](https://github.com/muan/hello-world) so it is now [zwirektech:patch-1](https://github.com/zwirektech/hello-world/tree/patch-1), accidentaly - GitHub has created it for me. 
- [change png image to size=50](https://github.com/zwirektech/hello-world/commit/cb8f6a217b33e73d6b01e519f079dcec45da2157)
- [sort humans.txt in alphabetical order](https://github.com/zwirektech/hello-world/commit/676c0e365cc7a157403e919c33050e2c790feb49)
- [move user files to humans directory](https://github.com/zwirektech/hello-world/commit/7d8f495f99da277c3a341ccb14719dfe91afdaca)
- update links in ReadMe files [acording to the history](https://github.com/zwirektech/hello-world/commits/gh-pages)

- and finally add [zwirektech to the maintainers list](https://github.com/zwirektech/hello-world/commit/46fef60b07521ed4d7f64495402dced22fc4a3c8) or not yet ? We'll see.

I've already created a new branch, intentionally this time, [patch-2-image](https://github.com/zwirektech/hello-world/commits/patch-2-image) but there is the first commit [update human.txt - add zwirektech](
https://github.com/zwirektech/hello-world/commit/f9b84f255341fcfd6bc4a103fae3d35c8dd6d983), which in this case would probably be in conflict in the future merge.
How can I roll back the changes in human.txt in my [patch-2-image](https://github.com/zwirektech/hello-world/commits/patch-2-image) ? 
Can I do it with the GitHub web interface? 
I'm also using git in command line and I've read a little about [git-revert](https://git-scm.com/docs/git-revert). Is this the right path to follow?
Any suggestion is welcome, since it has become pretty sophisticated learning.

**Comment by SubhrajyotiSen** [comment]
When you are creating a new branch, first go the master branch (or whichever is the main branch) and then create a new branch from that. This is will prevent your changes from another branch (of your fork) from being carried over to your new branch. 

Since you want to roll back to a particular commit, you can use the [git reset](https://git-scm.com/docs/git-reset) command.

And yes. You can selectively use your commits in different branches by using the [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) command.

**Comment by zwirektech** [comment]
Are we waiting here for [the change](https://github.com/muan/hello-world/pull/91#pullrequestreview-33926157) or for @aaossa to cancel the request according to @muan [explanation](https://github.com/muan/hello-world/pull/91#issuecomment-296108628)?

**Comment by SubhrajyotiSen** [comment]
We are actually waiting for the change. As in the addition of the file with your username.

**Review by SubhrajyotiSen — DISMISSED** [review]

**Review by SubhrajyotiSen — CHANGES_REQUESTED** [review]
Now that the repo structure has changed, the file needs to go in the humans directory

**Comment by zwirektech** [comment]
To humans directory..., right... Isn't it a job for GIT ?  
It says: "This branch has no conflicts with the base branch"
I'm confused now... ?

**Comment by SubhrajyotiSen** [comment]
Git will not automatically rearrange anything. You will need to manually place your file inside the directory.

**Comment by zwirektech** [comment]
Isn't it similar to the example described in [documentation](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#_basic_merging)?  
"[...]  
Figure 25. A merge commit  
It’s worth pointing out that Git determines the best common ancestor to use for its merge base  
[...]"

OK. I see it now. My PR would create the file zwirektech.html in the main directory. Tricky, isn't it?

**Comment by zwirektech** [comment]
Do I need to change anything else?

**Review by SubhrajyotiSen — APPROVED** [review]

**Comment by SubhrajyotiSen** [comment]
No. Everything is okay. I'll merge it now

**Pull request merged**
