### PR TITLE
HackNewbieBCU.md

### PR DESCRIPTION
**Pull request by R-Mct98**
message and picture inserted into separate page for test

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
Hey! Could you please change the filename to that of your username :smiley: 
And the picture you mentioned in the html will not be displayed since the path is relative to your computer. It needs to be an online image.

**Comment by SubhrajyotiSen** [comment]
Hey, the file name is still unchanged

**Comment by muan** [comment]
Hey @HackNewbieBCU, the file name should be `HackNewbieBCU.html`. Also fun fact I am from BCU (BIAD)!

**Comment by muan** [comment]
:wave: please send another pull request when you're ready! closing this for now.

**Pull request closed without merging**
