### PR TITLE
Add Sekihotai to human.txt and added Sekihotai.html

### PR DESCRIPTION
**Pull request by spiiritual**

### CODE REVIEW

**Comment by spiiritual** [comment]
accidentally put maintainers.md commit in this pull request instead of making seperate one

oops

**Comment by muan** [comment]
Hi! This looks good to me, but could you resolve the conflicts here so I can merge them? Thanks.

**Review by muan — CHANGES_REQUESTED** [review]
Hi! This looks good to me, but could you resolve the conflicts here so I can merge them? Thanks.

**Comment by spiiritual** [comment]
Is that good?

**Comment by spiiritual** [comment]
removed someone from maintainers.md because i dont know who they are and they don't appear to have made a pull request here

**Review by muan — APPROVED** [review]

**Comment by muan** [comment]
Thanks! Invite sent.

**Pull request merged**
