### PR TITLE
Create bigchief45.html

### PR DESCRIPTION
**Pull request by aalvrz**
This pull request:
- Adds `bigchief45.html` file.
- Modifies `humans.txt` file by adding "bigchief45" to the ordered list.

### CODE REVIEW

**Comment by aaossa** [comment]
Hi @BigChief45 , don't forget to add your name to human.txt :wink: Once you do that we will merge your PR. Also, please provide a description for your PR's :warning: Thanks!

**Comment by aalvrz** [comment]
Oops, Sorry about that, should be ok now I think.

**Comment by ghost** [comment]
Thanks @BigChief45 for your PR, **bigchief45.html** is now up [here](http://muan.co/hello-world/bigchief45.html). :octocat:

**Comment by aalvrz** [comment]
Awesome!

**Pull request merged**
