### PR TITLE
Add Username (SidOla)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
Hey! Can you also add a file under humans/ with your username

**Comment by ghost** [comment]
How do i do that??

**Comment by aaossa** [comment]
Add a commit to your branch. Once you do that, the commit will be added to your PR and we'll be able to merge your changes

**Comment by aaossa** [comment]
@SubhrajyotiSen can we close this? I don't remember if this changes are somewhere else. I'll close it because of inactivity, but if everything is ok let's open and merge this PR ;)

**Comment by SubhrajyotiSen** [comment]
Yes, we can close this since I had closed #110 considering this PR would serve the same purpose but this is inactive too.

**Pull request closed without merging**
