### PR TITLE
add list of maintainers

### PR DESCRIPTION
**Pull request by vyp**
Ref #8.

---

Do you mean something like `human.txt` for the list of maintainers?

### CODE REVIEW

**Comment by muan** [comment]
yep I think this would be enough, thanks.

one nit, since it's a markdown file, simply write @username would autolink, they dont need to be markdown links. :grimacing:

**Comment by vyp** [comment]
Ah I thought @-links don't work or something outside of issues/comments.

**Comment by muan** [comment]
Ugh wait, sorry, you're totally right, it doesn't.

**Comment by vyp** [comment]
Ah! Reverted, no worries.

**Comment by muan** [comment]
:sparkles:

**Comment by vyp** [comment]
Also, you can use reference style links instead if you don't like this style. I'll leave that to you. I just followed what was already used in the readme.

**Pull request merged**
