### PR TITLE
Add JeffChern.html

### PR DESCRIPTION
**Pull request by JeffChern**
This is my first time trying to PR.

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
Hey! Please take a look at your HTML file. The header tag got cut out

**Comment by JeffChern** [comment]
@SubhrajyotiSen  Oops, I've fixed it. Thank you!

**Comment by SubhrajyotiSen** [comment]
You forgot the opening <head> tag

**Comment by JeffChern** [comment]
@SubhrajyotiSen  Sigh.. Thanks a lot!

**Comment by aaossa** [comment]
Thanks for your PR @JeffChern :tada: :confetti_ball: :smile: . You can see your file [here](http://muan.co/hello-world/JeffChern.html)

**Pull request merged**
