### PR TITLE
Create nrk.html

### PR DESCRIPTION
**Pull request by nirajanrk**

### CODE REVIEW

**Review by aaossa — APPROVED** [review]

**Comment by aaossa** [comment]
Everything looks great! :raised_hand: Check your page [here](http://muan.github.io/hello-world/humans/nrk) :confetti_ball: :tada:

**Comment by SubhrajyotiSen** [comment]
Actually the filename should have been the same as the username right?

**Comment by aaossa** [comment]
🤔 That's right, I didn't check, sorry. I could push the changes in a few hours to fix it, if @nirajanrk agrees.

**Comment by nirajanrk** [comment]
Yes, that's fine. Thanks.

On Oct 30, 2017 1:17 PM, "Antonio Ossa" <notifications@github.com> wrote:

🤔 That's right, I didn't check, sorry. I could push the changes in a few
hours to fix it, if @nirajanrk <https://github.com/nirajanrk> agrees.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/muan/hello-world/pull/150#issuecomment-340517577>, or mute
the thread

**Pull request merged**
