### PR TITLE
updated name

### PR DESCRIPTION
**Pull request by ddemented**

### CODE REVIEW

**Comment by muan** [comment]
Hi there! The file name and the name you added to `human.txt` should be your GitHub username. Your username is `ddemented`!

**Comment by ddemented** [comment]
i did make the changes, now am not able to create a pull request, or push it, sorry newbie, need help with it

**Comment by muan** [comment]
No worries, what you did was correct! :100: There are just some conflicts that I'd have to fix.

**Comment by muan** [comment]
Merged! :tada: 
Your page: http://muan.co/hello-world/ddemented.html

**Pull request merged**
