### PR TITLE
Adding my user name to human.txt

### PR DESCRIPTION
**Pull request by ghost**
Brett88 is me

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
Hey! Can you also please add a file with your username as mentioned in the README? 😃

**Comment by ghost** [comment]
Just did it, sorry about that just getting my head around Github

**Comment by SubhrajyotiSen** [comment]
You can also push new commits to the same pull request by pushing the commits to the same branch. In your case, that's the patch-1. Why don't you try it here? 
Add your file as a new commit to the same branch. Then you will have a single pull request

**Comment by ghost** [comment]
I think i managed to add a another commit to patch 1

**Comment by SubhrajyotiSen** [comment]
Perfect! Well done.

**Pull request merged**
