### PR TITLE
Hello World

### PR DESCRIPTION
**Pull request by tankitt**
Plain old .html file.

### CODE REVIEW

**Comment by aaossa** [comment]
:wave: Hi @tankitt ! You forgot to add your username to `human.txt` :speak_no_evil: Please add a new commit and we'll merge your PR :grin: :raised_hands:

**Comment by tankitt** [comment]
Oh sorry!, im doing it right away thanks :)

**Comment by tankitt** [comment]
@aaossa can you check now ? thank.

**Comment by aaossa** [comment]
Yep, I'll merge it, but the best practice is to add a new commit in the same branch (in your case, the fork you made) so we just have 1 PR :thinking: But, don't worry, I'll merge both at the same time :grin: Thanks for your PR @tankitt :raised_hands:

**Comment by tankitt** [comment]
feels good. :)
i missed to add my username in the first time, but i couldn't find a way to edit my first PR and somehow my branch was not appearing so I ended making a new branch and new PR . Is there a way to edit the pull request? or am I left with creating a new branch only?
thanks a lot for your feedback 👍

**Pull request merged**
