### PR TITLE
add  information

### PR DESCRIPTION
**Pull request by zyxbest**
new file johnson.html
and new name in human.txt

### CODE REVIEW

**Comment by callumacrae** [comment]
Are you going to put anything in your johnson.html file? :scream:

Also, can you call it shengshuaijohnson.html and add yourself to the humans.txt as "shengshuaijohnson"?

**Comment by zyxbest** [comment]
okay……

**Comment by zyxbest** [comment]
Anybody  could check my request now?

**Comment by diezcami** [comment]
Looks good!

**Comment by callumacrae** [comment]
http://muan.co/hello-world/shengshuaijohnson.html :tada:

**Pull request merged**
