### PR TITLE
New member in human.txt and png size change. User files moved to humans.

### PR DESCRIPTION
**Pull request by zwirektech**
I wanted to create an html file for myself, but since it is not linked with the image on the main page (index.html) there is no point to do so.
Would it be a good idea to make a link under the image to the individual page?

### CODE REVIEW

**Comment by aaossa** [comment]
Well, you could create your html and we'll provide a link for you to see your page. This repo was created with educational purpouses but I agree that we could discuss about using the image to link with the created page. I think that's @muan decision :thinking:   

Also, why do you want to change the image size? Again, that's @muan decision :speak_no_evil: ...

**Comment by zwirektech** [comment]
I've changed the image size because I couldn't see what is on the picture.
Since this repo is for learning purposes I don't mind if someone will change it again to something more reasonable. The more you commit, the more you learn. 
And I don't think muan wants to decide of every branch merge...it's the job for collaborators, isn't it? 
As you said, this is a learning repo - let's learn.

The link on the picture is ok. I would just add a new one, under the picture to the html user file.

**Comment by zwirektech** [comment]
I think it's a good idea to have all the user files in one folder (humans). This is also a first step to make links to all files in this directory from the main page.

**Comment by SubhrajyotiSen** [comment]
Hey!
@zwirektech Thanks for the PR! Though are few things I would like to point out.

1. There are 4 logically different changes in this PR (adding your HTML file, adding yourself to list of maintainers, change in image size and change in repository structure). In most cases, it is a good idea to make separate PR for each such change.
2. You are right. The maintainers are there to take care of most of the details. We merge the PRs which follow the instructions mentioned in the README and also help out contributors with issues they face. But we leave the decisions regarding the functionality of the repo to muan. 
3. You can raise separate issues regarding the image size and change in repo structure. That will be a more appropriate place to discuss such changes in details. 

Hope this clears up everything 😃 I will be closing this PR to make way for structured discussions on your suggestions.

**Comment by zwirektech** [comment]
Hello @SubhrajyotiSen,
Thank you for your answer. This explains the matter.

**Comment by aaossa** [comment]
Can you please post an issue to discuss this before doing the changes?

**Comment by zwirektech** [comment]
Yes. I will. Lesson learned. I understand that even if something seems to be better it should be first discussed if it is better for all members.

**Pull request closed without merging**
