### PR TITLE
Added username and file

### PR DESCRIPTION
**Pull request by zotamias**

### CODE REVIEW

**Comment by aaossa** [comment]
Hi @zotamias ! 😁 Everything looks great, but you added a `.md` file. If you want to display your content in a prettier way, you could add a `.html` file instead. If you prefer to use your current file let us know to accept your PR. If we don't receive an answer in a few days, I think we'll merge this anyway. Remember to let us know your decision! 😱

**Comment by zotamias** [comment]
I actually do have an .html file that I can replace the .md file. 
Do you want me to update it & make a new commit?

**Comment by aaossa** [comment]
It's your choice 😁 If you use something like `.txt` or `.md` it should look like [this](http://muan.github.io/hello-world/humans/Sparker0i.txt), but if you use HTML you could use css and make it look 💯 👌 , like [this example](http://muan.github.io/hello-world/humans/leo424y.html). Choose the format you prefer but let me know to be able to merge your PR later 🙌

**Comment by aaossa** [comment]
Thanks @zotamias ! 🙌 Your page is live [here](http://muan.github.io/hello-world/humans/ZaraOtamias.html) 😁 Thanks for your contribution 👍 🎈 🎉 🎊

**Pull request merged**
