### PR TITLE
Create JasonTurley.md

### PR DESCRIPTION
**Pull request by JasonTurley**

### CODE REVIEW

**Comment by muan** [comment]
Hi Jason. Mind adding your username to `human.txt` too? Then you will be listed on http://muan.github.io/hello-world too!

**Comment by JasonTurley** [comment]
Added username. Thanks for replying! You’re an inspiration :)

**Comment by muan** [comment]
@JasonTurley :)
I meant adding your username to https://github.com/muan/hello-world/blob/gh-pages/human.txt < this file. Remember to keep it in alphabetical order.

**Comment by JasonTurley** [comment]
Fixed username issue

**Review by muan — APPROVED** [review]
💯💯💯

**Pull request merged**
