### PR TITLE
sync README with English version

### PR DESCRIPTION
**Pull request by clarkzjw**
just keep Chinese versions of README file (both **traditional** and **simplified**) update with English version :wink:

### CODE REVIEW

**Comment by clarkzjw** [comment]
Although I have been using GitHub for more than a year, but I haven't had much chance to pull request before. I still learnt a lot from this repo :sparkles: Thanks! :clap:

**Comment by muan** [comment]
Awesome! :sparkles: Thank you so much!

**Comment by muan** [comment]
This resolved #8! :heart:

**Comment by clarkzjw** [comment]
I'm glad that I could help out :innocent:

**Pull request merged**
